name: launch_args
description: Plugin to get command line launch args for both Android and iOS.
version: 2.0.0+1
homepage: https://github.com/peiffer-innovations/launch_args

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.pi.launchargs
        pluginClass: LaunchArgsPlugin
      ios:
        pluginClass: LaunchArgsPlugin
