name: launch_args
description: Plugin to get command line launch args for both Android and iOS.
version: 2.0.1
homepage: https://github.com/peiffer-innovations/launch_args

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=2.5.0'

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.pi.launchargs
        pluginClass: LaunchArgsPlugin
      ios:
        pluginClass: LaunchArgsPlugin
